from . import student
from . import course
from . import teacher
from . import schedule
from . import grade
from . import attendance
from . import res_partner
from . import grade_level
from . import student_group
from . import res_config_settings